### ISSUE TITLE
how to use with koa-pass ?

### ISSUE THREAD

**Issue by robbiemu** [f0rr0/koa-jsonwebtoken#4]
I'd love to use this with [koa-except](https://github.com/gingerich/koa-except):

```js
import jwt, { fromAuthorizationHeader, sign } from 'koa-jsonwebtoken';
jwt.except= require('koa-except')
//...
  app.use(
    jwt({
      secret: serverCredentials.shared, 
      extractToken: fromAuthorizationHeader
    })
//    .unless({ path: [/^\/(?!api)/] })
    .except({ method: 'GET', path: /^\/api\/Classes/ })
    .and({ method: 'GET', path: /^\/(?!api)/ })
  );
```

but I'm getting on npm start:
`Unhandled rejection TypeError: (0 , _koaJsonwebtoken2.default)(...).except is not a function
    at C:\Users\roberto\github\cmst385-accessibility\dist\server.js:125:4`

_note: originally this was about koa-pass, but then I manually hacked the uglified index for koa-jsonwebtoken, and found that 1. it works, and 2. except works better_

**Comment by robbiemu** [comment]
I can't run your build script, it is unix specific

**Comment by f0rr0** [comment]
@robbiemu apologies for not responding sooner. Were you able to solve the problem? As far as build scripts go, I think `rm -rf` is the culprit

**Comment by f0rr0** [comment]
@robbiemu Check if updated release builds on your non Unix machine. Let me know so that I can close this.

**Comment by robbiemu** [comment]
I did not get it to build. I manually edited the build out to use except instead. I will check in a couple days what the problem was again,  sorry I'm on vacation atm

**Comment by f0rr0** [comment]
@robbiemu closing this for now, feel free to reopen if you face issues.

**Comment by robbiemu** [comment]
please reopen. I'm sorry I was away and recently I have been busy writing essays.. going back to university...

anyway I did run the build again, afresh:

```
PS C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken> npm run build

> koa-jsonwebtoken@1.3.1 build C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
> npm run clean && $(npm bin)/webpack --env.prod


> koa-jsonwebtoken@1.3.1 clean C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
> $(npm bin)/rimraf ./build

'$' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "clean"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! koa-jsonwebtoken@1.3.1 clean: `$(npm bin)/rimraf ./build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koa-jsonwebtoken@1.3.1 clean script '$(npm bin)/rimraf ./build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the koa-jsonwebtoken package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     $(npm bin)/rimraf ./build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs koa-jsonwebtoken
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls koa-jsonwebtoken
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! koa-jsonwebtoken@1.3.1 build: `npm run clean && $(npm bin)/webpack --env.prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koa-jsonwebtoken@1.3.1 build script 'npm run clean && $(npm bin)/webpack --env.prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the koa-jsonwebtoken package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && $(npm bin)/webpack --env.prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs koa-jsonwebtoken
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls koa-jsonwebtoken
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken\npm-debug.log
```

here is the debug log it mentions I should attach:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle koa-jsonwebtoken@1.3.1~prebuild: koa-jsonwebtoken@1.3.1
6 silly lifecycle koa-jsonwebtoken@1.3.1~prebuild: no script for prebuild, continuing
7 info lifecycle koa-jsonwebtoken@1.3.1~build: koa-jsonwebtoken@1.3.1
8 verbose lifecycle koa-jsonwebtoken@1.3.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle koa-jsonwebtoken@1.3.1~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken\node_modules\.bin;C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Dell\DW WLAN Card;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Users\roberto\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\roberto\AppData\Local\Programs\Python\Python35\;C:\Ruby23-x64\bin;C:\Users\roberto\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\roberto\AppData\Roaming\npm;C:\Program Files\Heroku\bin;C:\Users\roberto\AppData\Local\atom\bin;.\node_modules\.bin
10 verbose lifecycle koa-jsonwebtoken@1.3.1~build: CWD: C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
11 silly lifecycle koa-jsonwebtoken@1.3.1~build: Args: [ '/d /s /c', 'npm run clean && $(npm bin)/webpack --env.prod' ]
12 silly lifecycle koa-jsonwebtoken@1.3.1~build: Returned: code: 1  signal: null
13 info lifecycle koa-jsonwebtoken@1.3.1~build: Failed to exec build script
14 verbose stack Error: koa-jsonwebtoken@1.3.1 build: `npm run clean && $(npm bin)/webpack --env.prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid koa-jsonwebtoken@1.3.1
16 verbose cwd C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error koa-jsonwebtoken@1.3.1 build: `npm run clean && $(npm bin)/webpack --env.prod`
22 error Exit status 1
23 error Failed at the koa-jsonwebtoken@1.3.1 build script 'npm run clean && $(npm bin)/webpack --env.prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the koa-jsonwebtoken package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run clean && $(npm bin)/webpack --env.prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs koa-jsonwebtoken
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls koa-jsonwebtoken
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

BTW, rimraf is globally available on my machine, as is the node_modules/.bin of whatever project I am in, so it is easy enough to just remove these `$(npm bin)` calls. But that still produces an error, which I will post in the next comment to keep this one from getting too long.

**Comment by robbiemu** [comment]
here's what happens when I resolve those paths (making sure to first `npm i -S es6-promisify jsonwebtoken koa-unless babel-core babel-loader babel-plugin-transform-async-to-generator koa`):
```
PS C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken> npm run build

> koa-jsonwebtoken@1.3.1 build C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
> npm run clean && webpack --env.prod


> koa-jsonwebtoken@1.3.1 clean C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
> rimraf ./build

Hash: 083512db5e3b24ab4c44
Version: webpack 2.2.1
Time: 121ms
       Asset     Size  Chunks             Chunk Names
    index.js  9.83 kB       0  [emitted]  index
index.js.map  9.24 kB       0  [emitted]  index
   [0] ../koa-except/index.js 1.48 kB {0} [built]
   [5] ./main.js 3.03 kB {0} [built]
    + 4 hidden modules

> koa-jsonwebtoken@1.3.1 postbuild C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken
> uglifyjs ./build/index.js -o ./build/index.js --source-map ./build/index.js.map --source-map-root ./main.js --in-sourc
e-map ./build/index.js.map --screw-ie8 -c -m

Parse error at ./build/index.js:188,75
Unexpected token: operator (>)
Error
    at new JS_Parse_Error (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:196:18)
    at js_error (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:204:11)
    at croak (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:680:9)
    at token_error (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:688:9)
    at unexpected (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:694:9)
    at expr_atom (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:1201:9)
    at maybe_unary (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:1363:19)
    at expr_ops (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:1398:24)
    at maybe_conditional (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:1403:20)
    at maybe_assign (C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\uglify-js\lib\parse.js:1427:20)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run
" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! koa-jsonwebtoken@1.3.1 postbuild: `uglifyjs ./build/index.js -o ./build/index.js --source-map ./build/index.js.
map --source-map-root ./main.js --in-source-map ./build/index.js.map --screw-ie8 -c -m`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koa-jsonwebtoken@1.3.1 postbuild script 'uglifyjs ./build/index.js -o ./build/index.js --source-m
ap ./build/index.js.map --source-map-root ./main.js --in-source-map ./build/index.js.map --screw-ie8 -c -m'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the koa-jsonwebtoken package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     uglifyjs ./build/index.js -o ./build/index.js --source-map ./build/index.js.map --source-map-root ./main.js
 --in-source-map ./build/index.js.map --screw-ie8 -c -m
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs koa-jsonwebtoken
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls koa-jsonwebtoken
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\roberto\github\koa-jsonwebtokentest\node_modules\koa-jsonwebtoken\npm-debug.log
```

the line in question reads:
`/* harmony default export */ __webpack_exports__["default"] = (opts = {}) => {`

which, to me, looks like valid javascript.

**Comment by f0rr0** [comment]
@robbiemu what's your node version?

**Comment by robbiemu** [comment]
7.4.0
